http:
  routers:
    dashboard:
      rule: HostRegexp(`traefik.*`) || (Host(`192.168.176.99`) && PathPrefix(`/dashboard`))
      service: api@internal

    tunnel-rtr:
      entryPoints: 
        - web
        - websecure
      rule: "HostRegexp(`tunnel.*`)"
      service: tunnel-svc

    # modem-rtr:
    #   entryPoints: 
    #     - web
    #     - websecure
    #   rule: "HostRegexp(`modem.*`)"
    #   service: modem-svc

    # mk-rtr:
    #   entryPoints: 
    #     - web
    #     - websecure
    #   rule: "HostRegexp(`mk.*`)"
    #   service: mk-svc


  services:
    tunnel-svc:
      loadBalancer:
        servers:
          - url: "http://127.0.0.1:11112/"

  #   modem-svc:
  #     loadBalancer:
  #       servers:
  #         - url: "http://192.168.184.1"

  #   mk-svc:
  #     loadBalancer:
  #       servers:
  #         - url: "http://127.0.0.1:8000/obs-comp/"
