http:
  routers:
    dashboard:
      rule: HostRegexp(`traefik.*`) && PathPrefix(`/dashboard`)
      service: api@internal

    portal-rtr:
      entryPoints: 
        - web
        - websecure
      rule: "HostRegexp(`portal.*`)"
      service: portal-svc

    sync-rtr:
      entryPoints: 
        - web
        - websecure
      rule: "HostRegexp(`sync.*`)"
      service: sync-svc

    jupyter-rtr:
      entryPoints: 
        - web
        - websecure
      rule: "HostRegexp(`jupyter.*`)"
      service: jupyter-svc

    tensorboard-rtr:
      entryPoints: 
        - web
        - websecure
      rule: "HostRegexp(`tensorboard.*`)"
      service: tensorboard-svc

    tunnel-rtr:
      entryPoints: 
        - web
        - websecure
      rule: "HostRegexp(`tunnel.*`)"
      service: tunnel-svc

    comfy-rtr:
      entryPoints: 
        - web
        - websecure
      rule: "HostRegexp(`comfy.*`)"
      service: comfy-svc

  services:
    portal-svc:
      loadBalancer:
        servers:
          - url: "http://127.0.0.1:11111"

    sync-svc:
      loadBalancer:
        servers:
          - url: "http://127.0.0.1:18384"

    jupyter-svc:
      loadBalancer:
        servers:
          - url: "http://127.0.0.1:18080"

    tensorboard-svc:
      loadBalancer:
        servers:
          - url: "http://127.0.0.1:16006"

    tunnel-svc:
      loadBalancer:
        servers:
          - url: "http://127.0.0.1:11112"

    comfy-svc:
      loadBalancer:
        servers:
          - url: "http://127.0.0.1:18188"